version: "3"

services:
  jupyterhub:
    build: .
    volumes:
     - ./config/jupyterhub_config.py:/home/jupyter/jupyterhub_config.py
    command:
     - "jupyterhub"
     - "--config=jupyterhub_config.py"
    ports:
      - "8000:8000"
